# Routing engine configuration
# Options: "valhalla" or "ors"
routing_engine: "valhalla"

# Valhalla configuration
valhalla:
  route_url: "http://localhost:8002/route"
  isochrone_url: "http://localhost:8002/isochrone"

# ORS configuration
ors:
  api_key: ""  # Add your API key here if using public ORS API
  route_url: "https://api.openrouteservice.org/v2/directions/foot-walking"
  isochrone_url: "https://api.openrouteservice.org/v2/isochrones/foot-walking"
  # For local ORS instance:
  # route_url: "http://localhost:8080/ors/v2/directions/foot-walking"
  # isochrone_url: "http://localhost:8080/ors/v2/isochrones/foot-walking"

# Optimization parameters
optimization:
  # Linear optimization parameters
  linear_optimisation:
    num_facilities: 12  # Number of NEW facilities to open
  
  # Clustering parameters
  clustering:
    # DBSCAN parameters
    dbscan:
      eps: 0.005  # Epsilon parameter for clustering
      min_samples: 20  # Minimum samples parameter
    
    # ORS clustering specific parameters
    clustering_ors:
      iso_threshold: 10  # Threshold for underserved buildings
  
# Data preparation parameters
data_preparation:
  # Population allocation parameters
  population_allocation:
    flats_under_construction: false
    flats_in_planning: false
    exclusion_buffer: 5 # if a new building is planned within this distance, the old one is excluded from the population allocation
    
  # Demand points parameters
  demand_points:
    n_clusters: 700  # Number of clusters for demand points
    
  # Potential sites parameters
  potential_sites:
    buffer_dist_vbz: 2      # meters buffer around VBZ infrastructure
    buffer_trees: 2         # meters buffer around trees
    max_slope: 5            # Maximum slope in degrees
    area_threshold: 16      # Minimum area in square meters
    buffer_buildings: 14    # meters buffer around buildings

# Sensitivity analysis parameters
sensitivity_analysis:
  # Cluster values to test
  clusters: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 150, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200, 1300, 1400, 1500]
  # Linear optimisation parameters for sensitivity analysis
  linear_optimisation:
    num_facilities: 12  # Number of facilities to open

# P-analysis parameters
p_analysis:
  range:
    start: 1   # Starting value
    end: 31    # Ending value (exclusive)
    step: 1    # Step size
  